version: '3'

# default build settings
x-build: &default-build
  context: .
  dockerfile: main.Dockerfile
  args:
    - BASE_IMAGE=nvidia/cuda:12.3.2-base-ubuntu22.04
    - &ssh-install WITH_SSH=true
    - WITH_ESSENTIAL_APPS=false
    - WITH_ADDITIONAL_APPS=false
    - &ssh-default-user SSH_USER_NAME=myssh # default ssh user name
    - &ssh-default-pw SSH_USER_PASSWORD=123456  # default ssh user password
    # - APT_SOURCE_FILE=/initscripts/sources-tsinghua.list  # change apt repo source file
    # - APT_HTTP_PROXY=http://host.docker.internal:30080  # set apt http proxy
    # - OPTIONAL_HTTP_PROXY=http://host.docker.internal:30080 # set optional http proxy used when needed

# image that uses gpu
x-gpu-image: &gpu-image
  stdin_open: true
  tty: true
  command: /bin/bash

  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [gpu]

# image that do not use gpu
x-cpu-image: &cpu-image
  stdin_open: true
  tty: true
  command: /bin/bash

services:
  nv-cu118:
    <<: *gpu-image
    image: mydev:cu118
    build:
      context: .
      dockerfile: main.Dockerfile
      args:
        - BASE_IMAGE=nvidia/cuda:11.8.0-base-ubuntu22.04
        - WITH_ESSENTIAL_APPS=true
        - APT_SOURCE_FILE=/initscripts/sources-tsinghua.list
        - OPTIONAL_HTTP_PROXY=http://host.docker.internal:30080
        - *ssh-install
        - *ssh-default-user
        - *ssh-default-pw

    