version: '3'
services:
  my_service:
    image: my_image:base
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
    - '12222:22'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
    environment: {}
    build:
      context: .
      dockerfile: stage_base.Dockerfile
      extra_hosts:
      - host.docker.internal:host-gateway
      args:
        BASE_IMAGE: nvidia/cuda:12.3.2-base-ubuntu22.04
        WITH_ESSENTIAL_APPS: true
        WITH_CUSTOM_APPS: true
        WITH_SSH: true
        SSH_USER_NAME: me
        SSH_USER_PASSWORD: 123456
        SSH_PUBKEY_FILE: ''
        APT_SOURCE_FILE: /installation/apt/sources-tsinghua.list
        KEEP_APT_SOURCE_FILE: true
        APT_USE_PROXY: false
        APT_KEEP_PROXY: false
        USER_HTTP_PROXY: http://host.docker.internal:7890
        USER_HTTPS_PROXY: http://host.docker.internal:7890
