site_name: PeiDocker

nav:
- Introduction: index.md
- Examples: examples.md
- Advanced Examples: advanced_examples.md

theme: readthedocs

plugins:
- search
- autorefs
- glightbox

markdown_extensions:
- attr_list
- md_in_html