site_name: PeiDocker
site_url: https://igamenovoer.github.io/PeiDocker/
repo_url: https://github.com/igamenovoer/PeiDocker
repo_name: PeiDocker

nav:
- Introduction: index.md
- CLI Reference: cli_reference.md
- Examples: examples.md
- Advanced Examples: advanced_examples.md

theme: readthedocs

plugins:
- search
- autorefs
- glightbox

markdown_extensions:
- attr_list
- md_in_html