site_name: PeiDocker
site_url: https://igamenovoer.github.io/PeiDocker/
site_dir: site
repo_url: https://github.com/igamenovoer/PeiDocker
repo_name: PeiDocker
use_directory_urls: true

nav:
- Introduction: index.md
- CLI Reference: cli_reference.md
- Examples:
  - Basic: examples/basic.md
  - Advanced: examples/advanced.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
- search
- autorefs
- glightbox

markdown_extensions:
- attr_list
- md_in_html
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
