#!/bin/bash

# create in-image storage paths
echo "creating hard storage directories"

mkdir -p $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_APPS 
chmod 777 $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_APPS
echo "created $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_APPS"

mkdir -p $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_DATA 
chmod 777 $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_DATA 
echo "created $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_DATA"

mkdir -p $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_WORKSPACE 
chmod 777 $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_WORKSPACE
echo "created $X_PATH_HARD_BASE/$X_PREFIX_IMAGE_STORAGE/$X_PREFIX_WORKSPACE"

mkdir -p $X_PATH_HARD_BASE/$X_PREFIX_VOLUME_STORAGE 
chmod 777 $X_PATH_HARD_BASE/$X_PREFIX_VOLUME_STORAGE
echo "created $X_PATH_HARD_BASE/$X_PREFIX_VOLUME_STORAGE"

# creating soft directories
echo "creating soft storage directories"

mkdir -p $X_PATH_SOFT_BASE
chmod 777 $X_PATH_SOFT_BASE
echo "created $X_PATH_SOFT_BASE"

# mkdir -p $X_PATH_SOFT_BASE/$X_PREFIX_APPS 
# chmod 777 $X_PATH_SOFT_BASE/$X_PREFIX_APPS 
# echo "created $X_PATH_SOFT_BASE/$X_PREFIX_APPS"

# mkdir -p $X_PATH_SOFT_BASE/$X_PREFIX_DATA 
# chmod 777 $X_PATH_SOFT_BASE/$X_PREFIX_DATA 
# echo "created $X_PATH_SOFT_BASE/$X_PREFIX_DATA"

# mkdir -p $X_PATH_SOFT_BASE/$X_PREFIX_WORKSPACE 
# chmod 777 $X_PATH_SOFT_BASE/$X_PREFIX_WORKSPACE
# echo "created $X_PATH_SOFT_BASE/$X_PREFIX_WORKSPACE"