stage_1:
  image:
    base: ubuntu:24.04
    output: pei-example-host-mount:stage-1
  ssh:
    enable: true
    port: 22
    host_port: 2224
    users:
      dev:
        password: "123456"

stage_2:
  image:
    output: pei-example-host-mount:stage-2
  storage:
    app:
      type: image
    data:
      type: image
    workspace:
      type: host
      host_path: "${HOST_WORKSPACE:-/tmp/peidocker-host-workspace}"
