stage_1:
  image:
    base: ubuntu:24.04
    output: pei-example-proxy:stage-1
  ssh:
    enable: true
    port: 22
    host_port: 2228
    users:
      dev:
        password: "123456"
  proxy:
    address: host.docker.internal
    port: 7890
    enable_globally: true
    remove_after_build: true
    use_https: false
  apt:
    repo_source: tuna
    use_proxy: true
    keep_proxy_after_build: false

stage_2:
  image:
    output: pei-example-proxy:stage-2
