"""
Version Information for PeiDocker Package.

This file is automatically generated by setuptools-scm and should not be
modified manually. It provides version information including development
versions with git commit details.

The version information is used throughout the package for:
- CLI version display (--version flag)
- Package metadata and distribution
- Development build identification
- GUI application about dialogs

Version Format
--------------
Production releases: "1.0.0"
Development builds: "1.0.dev123+g1234567.d20250101" where:
- 1.0: Base version
- dev123: Number of commits since last tag
- g1234567: Git commit hash (shortened)
- d20250101: Date of last commit

Warning
-------
This file is generated by setuptools-scm during package build.
Do not modify manually or track in version control.
"""

# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple"]

# Type checking imports for version tuple typing
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

# Version variables (populated by setuptools-scm)
version: str                     # String version (e.g., "1.0.0")
__version__: str                 # Same as version (standard Python convention)
__version_tuple__: VERSION_TUPLE # Tuple version (e.g., (1, 0, 0))
version_tuple: VERSION_TUPLE     # Same as __version_tuple__

# Version values (automatically updated by setuptools-scm)
__version__ = version = '0.1.dev203+g1109656.d20250723'
__version_tuple__ = version_tuple = (0, 1, 'dev203', 'g1109656.d20250723')
